name: ✨ Feature Request
description: Suggest an idea or enhancement for MarkView
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make MarkView better.

  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to see?
      description: Describe your idea clearly
      placeholder: I would like MarkView to support PlantUML diagrams...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      description: Explain the use case or problem this solves
      placeholder: This would help when creating technical documentation...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details, examples, or screenshots
      placeholder: Optional - Add mockups, examples, or links to similar features

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
