name: ✨ Feature Request
description: Suggest a new feature for MarkView
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input in making MarkView better.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's missing?
      placeholder: I'm always frustrated when I can't render PlantUML diagrams in my markdown files...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "How should this feature work? Describe your ideal user experience."
      placeholder: |
        Add PlantUML diagram rendering support:
        1. Detect ```plantuml code blocks in markdown
        2. Convert PlantUML syntax to SVG/PNG diagrams
        3. Display rendered diagrams inline (similar to Mermaid diagrams)
        4. Support common diagram types (class, sequence, activity, etc.)
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives & Examples (optional)
      description: |
        • What workarounds are you currently using?
        • Have you seen this feature in other tools?
        • Any additional context that might help?
      placeholder: |
        Current workaround: I use an external PlantUML server to generate images, then embed them manually
        Similar feature: VSCode Markdown Preview Enhanced and GitLab both support PlantUML rendering
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case (optional)
      description: "How often would you use this feature? In what scenarios?"
      placeholder: |
        I use this weekly for technical documentation and architecture diagrams
        PlantUML is standard in our team, and inline rendering would save manual image generation
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: I'm willing to provide feedback if this feature is implemented
