name: ❓ Question
description: Ask a question about MarkView
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about how MarkView works? We're here to help!
  
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about MarkView?
      placeholder: |
        Example: How do I download Mermaid diagrams as PNG or SVG?
        Be specific - the more details you provide, the better we can help!
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: What You've Tried (optional)
      description: |
        Have you tried anything already? What happened?
        This helps us give you a more relevant answer.
      placeholder: |
        I can see Mermaid diagrams rendered in the document
        I tried right-clicking on the diagram but couldn't find a download option
  
  - type: input
    id: version
    attributes:
      label: MarkView Version (if relevant)
      description: "🔍 Find this in the extension popup or Chrome Extensions page"
      placeholder: e.g., 1.0.4
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have checked the [documentation](https://getmarkview.com/support.html) and FAQs
          required: true
        - label: I have searched existing issues for similar questions
          required: true
