name: Welcome New Contributors
on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 **Thanks for opening your first issue!**

            I'll review this as soon as possible. In the meantime:

            - 📖 Check our [Support & FAQ](https://getmarkview.com/support) for common questions
            - ⭐ If you're enjoying MarkView, please consider leaving a review:
              - [Chrome Web Store](https://chromewebstore.google.com/detail/cfopbpknalachedpcddhgbgjoigklien)
              - [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/detail/kpobglkjeapfinbaecjidahlnnohcaed)

            Thanks for helping improve MarkView! 🚀
